//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMS_DeviceDetails
    {
        public int Id { get; set; }
        public int AreaId { get; set; }
        public int ParentID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string OEM { get; set; }
        public int Type { get; set; }
        public int State { get; set; }
        public string Remark { get; set; }
        public bool locking { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual EMS_DeviceArea EMS_DeviceArea { get; set; }
    }
}
