//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMS_DeviceState
    {
        public EMS_DeviceState()
        {
            this.EMS_DeviceDetails = new HashSet<EMS_DeviceDetails>();
        }
    
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<EMS_DeviceDetails> EMS_DeviceDetails { get; set; }
    }
}
