//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_External
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Remark { get; set; }
        public string Photo { get; set; }
        public string SysUserId { get; set; }
        public string TrueName { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
