//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_TASKJOBS
    {
        public JOB_TASKJOBS()
        {
            this.JOB_TASKJOBS_LOG = new HashSet<JOB_TASKJOBS_LOG>();
        }
    
        public string sno { get; set; }
        public string taskName { get; set; }
        public string Id { get; set; }
        public string taskTitle { get; set; }
        public string taskCmd { get; set; }
        public Nullable<System.DateTime> crtDt { get; set; }
        public Nullable<int> state { get; set; }
        public string creator { get; set; }
        public string procName { get; set; }
        public string procParams { get; set; }
    
        public virtual ICollection<JOB_TASKJOBS_LOG> JOB_TASKJOBS_LOG { get; set; }
    }
}
