//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_TASKJOBS_LOG
    {
        public int itemID { get; set; }
        public string sno { get; set; }
        public string taskName { get; set; }
        public string Id { get; set; }
        public Nullable<System.DateTime> executeDt { get; set; }
        public string executeStep { get; set; }
        public string result { get; set; }
    
        public virtual JOB_TASKJOBS JOB_TASKJOBS { get; set; }
    }
}
