//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_Article_Albums
    {
        public string Id { get; set; }
        public string ArticleId { get; set; }
        public string BigImg { get; set; }
        public string SmallImg { get; set; }
        public string Remark { get; set; }
    
        public virtual MIS_Article MIS_Article { get; set; }
    }
}
