//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_WebIM_RecentContact
    {
        public int Id { get; set; }
        public string ContactPersons { get; set; }
        public string UserId { get; set; }
        public System.DateTime InfoTime { get; set; }
        public string ContactPersonsTitle { get; set; }
    }
}
