//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_WebIM_Message
    {
        public MIS_WebIM_Message()
        {
            this.MIS_WebIM_Message_Rec = new HashSet<MIS_WebIM_Message_Rec>();
        }
    
        public string Id { get; set; }
        public string Message { get; set; }
        public string Sender { get; set; }
        public string receiver { get; set; }
        public bool State { get; set; }
        public Nullable<System.DateTime> SendDt { get; set; }
        public string receiverTitle { get; set; }
    
        public virtual ICollection<MIS_WebIM_Message_Rec> MIS_WebIM_Message_Rec { get; set; }
    }
}
