//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_WebIM_Message_Rec
    {
        public string MessageId { get; set; }
        public string receiver { get; set; }
        public bool State { get; set; }
        public Nullable<System.DateTime> RecDt { get; set; }
    
        public virtual MIS_WebIM_Message MIS_WebIM_Message { get; set; }
    }
}
