//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_Article_Comment
    {
        public string Id { get; set; }
        public string ArticleId { get; set; }
        public string UserId { get; set; }
        public string TrueName { get; set; }
        public string IP { get; set; }
        public string BodyContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> IsReply { get; set; }
        public string ReplyContent { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
    
        public virtual MIS_Article MIS_Article { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}
