//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_ContactCompanyCategory
    {
        public Spl_ContactCompanyCategory()
        {
            this.Spl_ContactCompany = new HashSet<Spl_ContactCompany>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Spl_ContactCompany> Spl_ContactCompany { get; set; }
    }
}
