//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_InOutCategory
    {
        public Spl_InOutCategory()
        {
            this.Spl_WarehouseWarrant = new HashSet<Spl_WarehouseWarrant>();
            this.Spl_WarehouseWarrantOUT = new HashSet<Spl_WarehouseWarrantOUT>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Spl_WarehouseWarrant> Spl_WarehouseWarrant { get; set; }
        public virtual ICollection<Spl_WarehouseWarrantOUT> Spl_WarehouseWarrantOUT { get; set; }
    }
}
