//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_WareUnitConvert
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string MainUnit { get; set; }
        public string AssistUnit { get; set; }
        public decimal ConvertRate { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
