//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_TestStudents
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public string Name { get; set; }
        public int Avg { get; set; }
        public string Photo { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Spl_TestClass Spl_TestClass { get; set; }
    }
}
