//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_WarehouseWarrantOUT
    {
        public Spl_WarehouseWarrantOUT()
        {
            this.Spl_WarehouseWarrantDetailsOUT = new HashSet<Spl_WarehouseWarrantDetailsOUT>();
        }
    
        public string Id { get; set; }
        public System.DateTime OutTime { get; set; }
        public string Handler { get; set; }
        public string Remark { get; set; }
        public decimal PriceTotal { get; set; }
        public int State { get; set; }
        public string Checker { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyPerson { get; set; }
        public bool Confirmation { get; set; }
        public string InOutCategoryId { get; set; }
        public string WarehouseId { get; set; }
        public string ContractNumber { get; set; }
    
        public virtual Spl_InOutCategory Spl_InOutCategory { get; set; }
        public virtual Spl_Warehouse Spl_Warehouse { get; set; }
        public virtual ICollection<Spl_WarehouseWarrantDetailsOUT> Spl_WarehouseWarrantDetailsOUT { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}
