//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_TestClass
    {
        public Spl_TestClass()
        {
            this.Spl_TestStudents = new HashSet<Spl_TestStudents>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<Spl_TestStudents> Spl_TestStudents { get; set; }
    }
}
