//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_Product
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string Color { get; set; }
        public decimal Number { get; set; }
        public string CategoryId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
    
        public virtual Spl_ProductCategory Spl_ProductCategory { get; set; }
    }
}
