//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_WareCategory
    {
        public Spl_WareCategory()
        {
            this.Spl_WareCategory1 = new HashSet<Spl_WareCategory>();
            this.Spl_WareDetails = new HashSet<Spl_WareDetails>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ParentId { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Enable { get; set; }
    
        public virtual ICollection<Spl_WareCategory> Spl_WareCategory1 { get; set; }
        public virtual Spl_WareCategory Spl_WareCategory2 { get; set; }
        public virtual ICollection<Spl_WareDetails> Spl_WareDetails { get; set; }
    }
}
