//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_WareCheckTotal
    {
        public string Id { get; set; }
        public string WareDetailsId { get; set; }
        public string WarehouseId { get; set; }
        public string Remark { get; set; }
        public decimal DiffQuantity { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public int State { get; set; }
        public string Creater { get; set; }
        public string Checker { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public bool Confirmation { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Spl_WareDetails Spl_WareDetails { get; set; }
        public virtual Spl_Warehouse Spl_Warehouse { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual SysUser SysUser1 { get; set; }
    }
}
