//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_WarehouseCategory
    {
        public Spl_WarehouseCategory()
        {
            this.Spl_Warehouse = new HashSet<Spl_Warehouse>();
        }
    
        public string Id { get; set; }
        public string Code { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string Sort { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Enable { get; set; }
    
        public virtual ICollection<Spl_Warehouse> Spl_Warehouse { get; set; }
    }
}
