//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_EarlyWareingGood
    {
        public string Id { get; set; }
        public string WareDetailsId { get; set; }
        public decimal LowNumber { get; set; }
        public decimal TotalNumber { get; set; }
        public string ProductType { get; set; }
        public decimal ProductPrice { get; set; }
        public decimal PriceTotal { get; set; }
        public string WarehouseId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Spl_WareDetails Spl_WareDetails { get; set; }
        public virtual Spl_Warehouse Spl_Warehouse { get; set; }
    }
}
