//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_WarehouseAllocation
    {
        public Spl_WarehouseAllocation()
        {
            this.Spl_WarehouseAllocationDetails = new HashSet<Spl_WarehouseAllocationDetails>();
        }
    
        public string Id { get; set; }
        public System.DateTime InTime { get; set; }
        public string Handler { get; set; }
        public string Remark { get; set; }
        public decimal PriceTotal { get; set; }
        public int State { get; set; }
        public string Checker { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyPerson { get; set; }
        public bool Confirmation { get; set; }
        public string FromWarehouseId { get; set; }
        public string ToWarehouseId { get; set; }
        public string ContractNumber { get; set; }
    
        public virtual Spl_Warehouse Spl_Warehouse { get; set; }
        public virtual Spl_Warehouse Spl_Warehouse1 { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual ICollection<Spl_WarehouseAllocationDetails> Spl_WarehouseAllocationDetails { get; set; }
    }
}
