//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_WareDetails
    {
        public Spl_WareDetails()
        {
            this.Spl_EarlyWareingGood = new HashSet<Spl_EarlyWareingGood>();
            this.Spl_WareCheckTotal = new HashSet<Spl_WareCheckTotal>();
            this.Spl_WarehouseAllocationDetails = new HashSet<Spl_WarehouseAllocationDetails>();
            this.Spl_WarehouseWarrantDetails = new HashSet<Spl_WarehouseWarrantDetails>();
            this.Spl_WarehouseWarrantDetailsOUT = new HashSet<Spl_WarehouseWarrantDetailsOUT>();
            this.Spl_WareStockPile = new HashSet<Spl_WareStockPile>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string BarCode { get; set; }
        public string WareCategoryId { get; set; }
        public string Unit { get; set; }
        public string Lable { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public string Remark { get; set; }
        public string Vender { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
        public string ComeFrom { get; set; }
        public Nullable<decimal> UpperLimit { get; set; }
        public Nullable<decimal> LowerLimit { get; set; }
        public Nullable<decimal> PrimeCost { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public Nullable<decimal> Price5 { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Photo3 { get; set; }
        public string Photo4 { get; set; }
        public string Photo5 { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<Spl_EarlyWareingGood> Spl_EarlyWareingGood { get; set; }
        public virtual Spl_WareCategory Spl_WareCategory { get; set; }
        public virtual ICollection<Spl_WareCheckTotal> Spl_WareCheckTotal { get; set; }
        public virtual ICollection<Spl_WarehouseAllocationDetails> Spl_WarehouseAllocationDetails { get; set; }
        public virtual ICollection<Spl_WarehouseWarrantDetails> Spl_WarehouseWarrantDetails { get; set; }
        public virtual ICollection<Spl_WarehouseWarrantDetailsOUT> Spl_WarehouseWarrantDetailsOUT { get; set; }
        public virtual ICollection<Spl_WareStockPile> Spl_WareStockPile { get; set; }
    }
}
