//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_ProductCategory
    {
        public Spl_ProductCategory()
        {
            this.Spl_Product = new HashSet<Spl_Product>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
    
        public virtual ICollection<Spl_Product> Spl_Product { get; set; }
    }
}
