//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysAreas
    {
        public SysAreas()
        {
            this.SysAreas1 = new HashSet<SysAreas>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string ParentId { get; set; }
        public int Sort { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsMunicipality { get; set; }
        public bool IsHKMT { get; set; }
        public bool IsOther { get; set; }
    
        public virtual ICollection<SysAreas> SysAreas1 { get; set; }
        public virtual SysAreas SysAreas2 { get; set; }
    }
}
