//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysPosition
    {
        public SysPosition()
        {
            this.SysUser = new HashSet<SysUser>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Enable { get; set; }
        public int MemberCount { get; set; }
        public string DepId { get; set; }
    
        public virtual SysStruct SysStruct { get; set; }
        public virtual ICollection<SysUser> SysUser { get; set; }
    }
}
