//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysStruct
    {
        public SysStruct()
        {
            this.SysPosition = new HashSet<SysPosition>();
            this.SysStruct1 = new HashSet<SysStruct>();
            this.SysUser = new HashSet<SysUser>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string ParentId { get; set; }
        public int Sort { get; set; }
        public string Higher { get; set; }
        public bool Enable { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<SysPosition> SysPosition { get; set; }
        public virtual ICollection<SysStruct> SysStruct1 { get; set; }
        public virtual SysStruct SysStruct2 { get; set; }
        public virtual ICollection<SysUser> SysUser { get; set; }
    }
}
