//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WC_Group
    {
        public WC_Group()
        {
            this.WC_User = new HashSet<WC_User>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public string OfficalAccountId { get; set; }
    
        public virtual WC_OfficalAccounts WC_OfficalAccounts { get; set; }
        public virtual ICollection<WC_User> WC_User { get; set; }
    }
}
