//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WC_ResponseLog
    {
        public string Id { get; set; }
        public string OfficalAccountId { get; set; }
        public string OpenId { get; set; }
        public Nullable<int> RequestType { get; set; }
        public string RequestContent { get; set; }
        public Nullable<int> ResponseType { get; set; }
        public string ResponseContent { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual WC_OfficalAccounts WC_OfficalAccounts { get; set; }
    }
}
