//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WC_User
    {
        public string Id { get; set; }
        public string OpenId { get; set; }
        public string NickName { get; set; }
        public int Sex { get; set; }
        public string Language { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string HeadImgUrl { get; set; }
        public System.DateTime SubscribeTime { get; set; }
        public string UnionId { get; set; }
        public string Remark { get; set; }
        public string GroupId { get; set; }
        public string TagidList { get; set; }
        public int Subscribe { get; set; }
        public string OfficalAccountId { get; set; }
    
        public virtual WC_Group WC_Group { get; set; }
        public virtual WC_OfficalAccounts WC_OfficalAccounts { get; set; }
    }
}
