//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.IDAL.MIS
{
	public partial interface IMIS_Article_AlbumsRepository:IBaseRepository<MIS_Article_Albums>
	{
	
	}
}
