//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.IDAL.Spl
{
	public partial interface ISpl_WareDetailsRepository:IBaseRepository<Spl_WareDetails>
	{
	
	}
}
