//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Unity.Attributes;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using LinqToExcel;
using System.IO;
using System.Text;
using Apps.IDAL.EMS;
using Apps.Models.EMS;
using Apps.IBLL.EMS;
namespace Apps.BLL.EMS
{
	public partial class EMS_DeviceAreaBLL: Virtual_EMS_DeviceAreaBLL,IEMS_DeviceAreaBLL
	{
        

	}
	public class Virtual_EMS_DeviceAreaBLL
	{
        [Dependency]
        public IEMS_DeviceAreaRepository m_Rep { get; set; }

		public virtual List<EMS_DeviceAreaModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<EMS_DeviceArea> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.ParentId.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }

		public virtual List<EMS_DeviceAreaModel> GetListByUserId(ref GridPager pager, string userId,string queryStr)
		{
			return new List<EMS_DeviceAreaModel>();
		}
		
		public virtual List<EMS_DeviceAreaModel> GetListByParentId(ref GridPager pager, string queryStr,object parentId)
        {
			return new List<EMS_DeviceAreaModel>();
		}

        public virtual List<EMS_DeviceAreaModel> CreateModelList(ref IQueryable<EMS_DeviceArea> queryData)
        {

            List<EMS_DeviceAreaModel> modelList = (from r in queryData
                                              select new EMS_DeviceAreaModel
                                              {
													Id = r.Id,
													ParentId = r.ParentId,
													Name = r.Name,
													CreateTime = r.CreateTime,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, EMS_DeviceAreaModel model)
        {
            try
            {
                EMS_DeviceArea entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new EMS_DeviceArea();
               				entity.Id = model.Id;
				entity.ParentId = model.ParentId;
				entity.Name = model.Name;
				entity.CreateTime = model.CreateTime;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, object id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, object[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, EMS_DeviceAreaModel model)
        {
            try
            {
                EMS_DeviceArea entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.ParentId = model.ParentId;
				entity.Name = model.Name;
				entity.CreateTime = model.CreateTime;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual EMS_DeviceAreaModel GetById(object id)
        {
            if (IsExists(id))
            {
                EMS_DeviceArea entity = m_Rep.GetById(id);
                EMS_DeviceAreaModel model = new EMS_DeviceAreaModel();
                              				model.Id = entity.Id;
				model.ParentId = entity.ParentId;
				model.Name = entity.Name;
				model.CreateTime = entity.CreateTime;
 
                return model;
            }
            else
            {
                return null;
            }
        }


		 /// <summary>
        /// 校验Excel数据,这个方法一般用于重写校验逻辑
        /// </summary>
        public virtual bool CheckImportData(string fileName, List<EMS_DeviceAreaModel> list,ref ValidationErrors errors )
        {
          
            var targetFile = new FileInfo(fileName);

            if (!targetFile.Exists)
            {

                errors.Add("导入的数据文件不存在");
                return false;
            }

            var excelFile = new ExcelQueryFactory(fileName);

            //对应列头
			 				 excelFile.AddMapping<EMS_DeviceAreaModel>(x => x.ParentId, "ParentId");
				 excelFile.AddMapping<EMS_DeviceAreaModel>(x => x.Name, "Name");
				 excelFile.AddMapping<EMS_DeviceAreaModel>(x => x.CreateTime, "CreateTime");
 
            //SheetName
            var excelContent = excelFile.Worksheet<EMS_DeviceAreaModel>(0);
            int rowIndex = 1;
            //检查数据正确性
            foreach (var row in excelContent)
            {
                var errorMessage = new StringBuilder();
                var entity = new EMS_DeviceAreaModel();
						 				  entity.Id = row.Id;
				  entity.ParentId = row.ParentId;
				  entity.Name = row.Name;
				  entity.CreateTime = row.CreateTime;
 
                //=============================================================================
                if (errorMessage.Length > 0)
                {
                    errors.Add(string.Format(
                        "第 {0} 列发现错误：{1}{2}",
                        rowIndex,
                        errorMessage,
                        "<br/>"));
                }
                list.Add(entity);
                rowIndex += 1;
            }
            if (errors.Count > 0)
            {
                return false;
            }
            return true;
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        public virtual void SaveImportData(IEnumerable<EMS_DeviceAreaModel> list)
        {
            try
            {
                using (DBContainer db = new DBContainer())
                {
                    foreach (var model in list)
                    {
                        EMS_DeviceArea entity = new EMS_DeviceArea();
                       						entity.Id = ResultHelper.NewId;
						entity.ParentId = model.ParentId;
						entity.Name = model.Name;
						entity.CreateTime = ResultHelper.NowTime;
 
                        db.EMS_DeviceArea.Add(entity);
                    }
                    db.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                throw;
            }
        }
		public virtual bool Check(ref ValidationErrors errors, object id,int flag)
        {
			return true;
		}

        public virtual bool IsExists(object id)
        {
            return m_Rep.IsExist(id);
        }
		
		public void Dispose()
        { 
            
        }

	}
}
