//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.EMS;
using Apps.IDAL.EMS;
using System;
namespace Apps.DAL.EMS
{
	public partial class EMS_DeviceStateRepository:BaseRepository<EMS_DeviceState>,IEMS_DeviceStateRepository,IDisposable
	{
	    public EMS_DeviceStateRepository(DBContainer db):base(db)
        {
        
        }
	}
}
