//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.Flow;
using Apps.IDAL.Flow;
using System;
namespace Apps.DAL.Flow
{
	public partial class Flow_StepRuleRepository:BaseRepository<Flow_StepRule>,IFlow_StepRuleRepository,IDisposable
	{
	    public Flow_StepRuleRepository(DBContainer db):base(db)
        {
        
        }
	}
}
