//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.JOB;
using Apps.IDAL.JOB;
using System;
namespace Apps.DAL.JOB
{
	public partial class JOB_TASKJOBS_LOGRepository:BaseRepository<JOB_TASKJOBS_LOG>,IJOB_TASKJOBS_LOGRepository,IDisposable
	{
	    public JOB_TASKJOBS_LOGRepository(DBContainer db):base(db)
        {
        
        }
	}
}
