//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.MIS;
using Apps.IDAL.MIS;
using System;
namespace Apps.DAL.MIS
{
	public partial class MIS_ArticleRepository:BaseRepository<MIS_Article>,IMIS_ArticleRepository,IDisposable
	{
	    public MIS_ArticleRepository(DBContainer db):base(db)
        {
        
        }
	}
}
