//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.Spl;
using Apps.IDAL.Spl;
using System;
namespace Apps.DAL.Spl
{
	public partial class Spl_ProductCategoryRepository:BaseRepository<Spl_ProductCategory>,ISpl_ProductCategoryRepository,IDisposable
	{
	    public Spl_ProductCategoryRepository(DBContainer db):base(db)
        {
        
        }
	}
}
