//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.Sys;
using Apps.IDAL.Sys;
using System;
namespace Apps.DAL.Sys
{
	public partial class SysModuleRepository:BaseRepository<SysModule>,ISysModuleRepository,IDisposable
	{
	    public SysModuleRepository(DBContainer db):base(db)
        {
        
        }
	}
}
