//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.WC;
using Apps.IDAL.WC;
using System;
namespace Apps.DAL.WC
{
	public partial class WC_OfficalAccountsRepository:BaseRepository<WC_OfficalAccounts>,IWC_OfficalAccountsRepository,IDisposable
	{
	    public WC_OfficalAccountsRepository(DBContainer db):base(db)
        {
        
        }
	}
}
