//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysModuleModel:Virtual_SysModuleModel
	{
		
	}
	public class Virtual_SysModuleModel
	{
		[Display(Name = "GUID")]
		public virtual string Id { get; set; }
		[Display(Name = "模块名称")]
		public virtual string Name { get; set; }
		[Display(Name = "英文名称")]
		public virtual string EnglishName { get; set; }
		[Display(Name = "上级ID")]
		public virtual string ParentId { get; set; }
		[Display(Name = "URL")]
		public virtual string Url { get; set; }
		[Display(Name = "图标")]
		public virtual string Iconic { get; set; }
		[Display(Name = "排序")]
		public virtual Nullable<int> Sort { get; set; }
		[Display(Name = "说明")]
		public virtual string Remark { get; set; }
		[Display(Name = "是否启用")]
		public virtual bool Enable { get; set; }
		[Display(Name = "创建")]
		public virtual string CreatePerson { get; set; }
		[Display(Name = "创建时间")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		[Display(Name = "是否最后一项")]
		public virtual bool IsLast { get; set; }
		[Display(Name = "版本")]
		public virtual byte[] Version { get; set; }
		}
}
