//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Flow
{

	public partial class Flow_FormContentModel:Virtual_Flow_FormContentModel
	{
		
	}
	public class Virtual_Flow_FormContentModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "标题")]
		public virtual string Title { get; set; }
		[Display(Name = "发起用户")]
		public virtual string UserId { get; set; }
		[Display(Name = "对应表单")]
		public virtual string FormId { get; set; }
		[Display(Name = "公文级别")]
		public virtual string FormLevel { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "字段A的值")]
		public virtual string AttrA { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrB { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrC { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrD { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrE { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrF { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrG { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrH { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrI { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrJ { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrK { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrL { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrM { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrN { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrO { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrP { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrQ { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrR { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrS { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrT { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrU { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrV { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrW { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrX { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrY { get; set; }
		[Display(Name = "字段Z的值")]
		public virtual string AttrZ { get; set; }
		[Display(Name = "指定审核人")]
		public virtual string CustomMember { get; set; }
		[Display(Name = "截止时间")]
		public virtual System.DateTime TimeOut { get; set; }
		[Display(Name = "是否已删除")]
		public virtual bool IsDelete { get; set; }
		}
}
