//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_WareUnitConvertModel:Virtual_Spl_WareUnitConvertModel
	{
		
	}
	public class Virtual_Spl_WareUnitConvertModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "换算名称")]
		public virtual string Name { get; set; }
		[Display(Name = "主计量单位")]
		public virtual string MainUnit { get; set; }
		[Display(Name = "辅计量单位")]
		public virtual string AssistUnit { get; set; }
		[Display(Name = "换算率")]
		public virtual decimal ConvertRate { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
