//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.MIS
{

	public partial class MIS_Article_CategoryModel:Virtual_MIS_Article_CategoryModel
	{
		
	}
	public class Virtual_MIS_Article_CategoryModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "所属栏目")]
		public virtual Nullable<int> ChannelId { get; set; }
		[Display(Name = "类别名称")]
		public virtual string Name { get; set; }
		[Display(Name = "上级ID")]
		public virtual string ParentId { get; set; }
		[Display(Name = "排序")]
		public virtual Nullable<int> Sort { get; set; }
		[Display(Name = "类别配图")]
		public virtual string ImgUrl { get; set; }
		[Display(Name = "说明")]
		public virtual string BodyContent { get; set; }
		[Display(Name = "创建时间")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		[Display(Name = "是否启用")]
		public virtual bool Enable { get; set; }
		}
}
