//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysSettingsModel:Virtual_SysSettingsModel
	{
		
	}
	public class Virtual_SysSettingsModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "名称")]
		public virtual string Name { get; set; }
		[Display(Name = "类型")]
		public virtual string Type { get; set; }
		[Display(Name = "参数")]
		public virtual string Parameter { get; set; }
		[Display(Name = "说明")]
		public virtual string ReMark { get; set; }
		}
}
