//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysPositionModel:Virtual_SysPositionModel
	{
		
	}
	public class Virtual_SysPositionModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "职位名称")]
		public virtual string Name { get; set; }
		[Display(Name = "职位说明")]
		public virtual string Remark { get; set; }
		[Display(Name = "排序")]
		public virtual int Sort { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "状态")]
		public virtual bool Enable { get; set; }
		[Display(Name = "职位允许人数")]
		public virtual int MemberCount { get; set; }
		[Display(Name = "所属部门")]
		public virtual string DepId { get; set; }
		}
}
