//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.MIS
{

	public partial class MIS_WebIM_RecentContactModel:Virtual_MIS_WebIM_RecentContactModel
	{
		
	}
	public class Virtual_MIS_WebIM_RecentContactModel
	{
		[Display(Name = "未设置")]
		public virtual int Id { get; set; }
		[Display(Name = "以代码显示")]
		public virtual string ContactPersons { get; set; }
		[Display(Name = "未设置")]
		public virtual string UserId { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime InfoTime { get; set; }
		[Display(Name = "以名称显示")]
		public virtual string ContactPersonsTitle { get; set; }
		}
}
