//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Flow
{

	public partial class Flow_FormAttrModel:Virtual_Flow_FormAttrModel
	{
		
	}
	public class Virtual_Flow_FormAttrModel
	{
		[Display(Name = "ID")]
		public virtual string Id { get; set; }
		[Display(Name = "字段标题")]
		public virtual string Title { get; set; }
		[Display(Name = "字段英文名称")]
		public virtual string Name { get; set; }
		[Display(Name = "文本,日期,数字,多行文本")]
		public virtual string AttrType { get; set; }
		[Display(Name = "校验规则")]
		public virtual string CheckRule { get; set; }
		[Display(Name = "辅助JS脚本")]
		public virtual string CheckJS { get; set; }
		[Display(Name = "所属类别")]
		public virtual string TypeId { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "下拉框的值")]
		public virtual string OptionList { get; set; }
		}
}
