//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.MIS
{

	public partial class MIS_WebIM_MessageModel:Virtual_MIS_WebIM_MessageModel
	{
		
	}
	public class Virtual_MIS_WebIM_MessageModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string Message { get; set; }
		[Display(Name = "未设置")]
		public virtual string Sender { get; set; }
		[Display(Name = "以代码显示")]
		public virtual string receiver { get; set; }
		[Display(Name = "即时=0，推迟=1")]
		public virtual bool State { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<System.DateTime> SendDt { get; set; }
		[Display(Name = "以名称显示")]
		public virtual string receiverTitle { get; set; }
		}
}
