//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.EMS
{

	public partial class EMS_DeviceDetailsModel:Virtual_EMS_DeviceDetailsModel
	{
		
	}
	public class Virtual_EMS_DeviceDetailsModel
	{
		[Display(Name = "主键ID")]
		public virtual int Id { get; set; }
		[Display(Name = "区域ID")]
		public virtual int AreaId { get; set; }
		[Display(Name = "父级ID")]
		public virtual int ParentID { get; set; }
		[Display(Name = "设备编码")]
		public virtual string Code { get; set; }
		[Display(Name = "设备名称")]
		public virtual string Name { get; set; }
		[Display(Name = "设备型号")]
		public virtual string Model { get; set; }
		[Display(Name = "生产厂家")]
		public virtual string OEM { get; set; }
		[Display(Name = "设备类型")]
		public virtual int Type { get; set; }
		[Display(Name = "设备状态")]
		public virtual int State { get; set; }
		[Display(Name = "备注")]
		public virtual string Remark { get; set; }
		[Display(Name = "未设置")]
		public virtual bool locking { get; set; }
		[Display(Name = "未设置")]
		public virtual string CreateUser { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
