//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysSampleModel:Virtual_SysSampleModel
	{
		
	}
	public class Virtual_SysSampleModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "名称")]
		public virtual string Name { get; set; }
		[Display(Name = "年龄")]
		public virtual Nullable<int> Age { get; set; }
		[Display(Name = "生日")]
		public virtual Nullable<System.DateTime> Bir { get; set; }
		[Display(Name = "照片")]
		public virtual string Photo { get; set; }
		[Display(Name = "说明")]
		public virtual string Note { get; set; }
		[Display(Name = "创建时间")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		}
}
