//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_TestStudentsModel:Virtual_Spl_TestStudentsModel
	{
		
	}
	public class Virtual_Spl_TestStudentsModel
	{
		[Display(Name = "ID")]
		public virtual int Id { get; set; }
		[Display(Name = "所属班级")]
		public virtual int ClassId { get; set; }
		[Display(Name = "姓名")]
		public virtual string Name { get; set; }
		[Display(Name = "年龄")]
		public virtual int Avg { get; set; }
		[Display(Name = "头像")]
		public virtual string Photo { get; set; }
		[Display(Name = "状态")]
		public virtual bool Enable { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
