//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_WarehouseCategoryModel:Virtual_Spl_WarehouseCategoryModel
	{
		
	}
	public class Virtual_Spl_WarehouseCategoryModel
	{
		[Display(Name = "主键")]
		public virtual string Id { get; set; }
		[Display(Name = "代号")]
		public virtual string Code { get; set; }
		[Display(Name = "分类")]
		public virtual string Category { get; set; }
		[Display(Name = "出入库名称")]
		public virtual string Name { get; set; }
		[Display(Name = "排序")]
		public virtual string Sort { get; set; }
		[Display(Name = "备注")]
		public virtual string Remark { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "是否启用")]
		public virtual bool Enable { get; set; }
		}
}
