//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.JOB
{

	public partial class JOB_TASKJOBSModel:Virtual_JOB_TASKJOBSModel
	{
		
	}
	public class Virtual_JOB_TASKJOBSModel
	{
		[Display(Name = "ID主键")]
		public virtual string sno { get; set; }
		[Display(Name = "任务名称")]
		public virtual string taskName { get; set; }
		[Display(Name = "任务ID")]
		public virtual string Id { get; set; }
		[Display(Name = "任务标题")]
		public virtual string taskTitle { get; set; }
		[Display(Name = "任务命令")]
		public virtual string taskCmd { get; set; }
		[Display(Name = "创建时间")]
		public virtual Nullable<System.DateTime> crtDt { get; set; }
		[Display(Name = "状态")]
		public virtual Nullable<int> state { get; set; }
		[Display(Name = "创建人")]
		public virtual string creator { get; set; }
		[Display(Name = "进程")]
		public virtual string procName { get; set; }
		[Display(Name = "进程参数")]
		public virtual string procParams { get; set; }
		}
}
