//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_WarehouseWarrantDetailsOUTModel:Virtual_Spl_WarehouseWarrantDetailsOUTModel
	{
		
	}
	public class Virtual_Spl_WarehouseWarrantDetailsOUTModel
	{
		[Display(Name = "GUI主键")]
		public virtual string Id { get; set; }
		[Display(Name = "商品")]
		public virtual string WareDetailsId { get; set; }
		[Display(Name = "仓库名称")]
		public virtual string WarehouseId { get; set; }
		[Display(Name = "出库单号")]
		public virtual string WarehouseWarrantId { get; set; }
		[Display(Name = "数量")]
		public virtual decimal Quantity { get; set; }
		[Display(Name = "价格")]
		public virtual decimal Price { get; set; }
		[Display(Name = "总价")]
		public virtual decimal TotalPrice { get; set; }
		[Display(Name = "未设置")]
		public virtual string Defined { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
