//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.MIS
{

	public partial class MIS_Article_CommentModel:Virtual_MIS_Article_CommentModel
	{
		
	}
	public class Virtual_MIS_Article_CommentModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "所属文章")]
		public virtual string ArticleId { get; set; }
		[Display(Name = "发布者")]
		public virtual string UserId { get; set; }
		[Display(Name = "姓名")]
		public virtual string TrueName { get; set; }
		[Display(Name = "IP")]
		public virtual string IP { get; set; }
		[Display(Name = "内容")]
		public virtual string BodyContent { get; set; }
		[Display(Name = "创建时间")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		[Display(Name = "是否回复")]
		public virtual Nullable<int> IsReply { get; set; }
		[Display(Name = "回复内容")]
		public virtual string ReplyContent { get; set; }
		[Display(Name = "回复时间")]
		public virtual Nullable<System.DateTime> ReplyTime { get; set; }
		}
}
