//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysStructModel:Virtual_SysStructModel
	{
		
	}
	public class Virtual_SysStructModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "名称")]
		public virtual string Name { get; set; }
		[Display(Name = "上级ID")]
		public virtual string ParentId { get; set; }
		[Display(Name = "排序")]
		public virtual int Sort { get; set; }
		[Display(Name = "领导")]
		public virtual string Higher { get; set; }
		[Display(Name = "是否启用")]
		public virtual bool Enable { get; set; }
		[Display(Name = "说明")]
		public virtual string Remark { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
