//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysModuleDataFilterModel:Virtual_SysModuleDataFilterModel
	{
		
	}
	public class Virtual_SysModuleDataFilterModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "字段中文名称")]
		public virtual string Name { get; set; }
		[Display(Name = "字段")]
		public virtual string KeyCode { get; set; }
		[Display(Name = "对应模块")]
		public virtual string ModuleId { get; set; }
		[Display(Name = "是否验证（暂时不用）")]
		public virtual bool IsValid { get; set; }
		[Display(Name = "排序")]
		public virtual int Sort { get; set; }
		}
}
