//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysRightModel:Virtual_SysRightModel
	{
		
	}
	public class Virtual_SysRightModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "模块ID")]
		public virtual string ModuleId { get; set; }
		[Display(Name = "角色组ID")]
		public virtual string RoleId { get; set; }
		[Display(Name = "是否有权限")]
		public virtual bool Rightflag { get; set; }
		}
}
