//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysAreasModel:Virtual_SysAreasModel
	{
		
	}
	public class Virtual_SysAreasModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string Name { get; set; }
		[Display(Name = "未设置")]
		public virtual string ParentId { get; set; }
		[Display(Name = "未设置")]
		public virtual int Sort { get; set; }
		[Display(Name = "未设置")]
		public virtual bool Enable { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "直辖市")]
		public virtual bool IsMunicipality { get; set; }
		[Display(Name = "港澳台")]
		public virtual bool IsHKMT { get; set; }
		[Display(Name = "其他")]
		public virtual bool IsOther { get; set; }
		}
}
