//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.JOB
{

	public partial class JOB_TASKJOBS_LOGModel:Virtual_JOB_TASKJOBS_LOGModel
	{
		
	}
	public class Virtual_JOB_TASKJOBS_LOGModel
	{
		[Display(Name = "ID")]
		public virtual int itemID { get; set; }
		[Display(Name = "ID")]
		public virtual string sno { get; set; }
		[Display(Name = "任务名称")]
		public virtual string taskName { get; set; }
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "执行日期")]
		public virtual Nullable<System.DateTime> executeDt { get; set; }
		[Display(Name = "执行步骤")]
		public virtual string executeStep { get; set; }
		[Display(Name = "执行结果")]
		public virtual string result { get; set; }
		}
}
