//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_ContactCompanyCategoryModel:Virtual_Spl_ContactCompanyCategoryModel
	{
		
	}
	public class Virtual_Spl_ContactCompanyCategoryModel
	{
		[Display(Name = "主键ID")]
		public virtual string Id { get; set; }
		[Display(Name = "单位类别")]
		public virtual string Name { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "客户or供应商")]
		public virtual string Category { get; set; }
		}
}
