//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.EMS
{

	public partial class EMS_DeviceAreaModel:Virtual_EMS_DeviceAreaModel
	{
		
	}
	public class Virtual_EMS_DeviceAreaModel
	{
		[Display(Name = "主键ID")]
		public virtual int Id { get; set; }
		[Display(Name = "区域父ID")]
		public virtual int ParentId { get; set; }
		[Display(Name = "区域名称")]
		public virtual string Name { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
