//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.MIS
{

	public partial class MIS_WebIM_Message_RecModel:Virtual_MIS_WebIM_Message_RecModel
	{
		
	}
	public class Virtual_MIS_WebIM_Message_RecModel
	{
		[Display(Name = "未设置")]
		public virtual string MessageId { get; set; }
		[Display(Name = "未设置")]
		public virtual string receiver { get; set; }
		[Display(Name = "0未读，1已读")]
		public virtual bool State { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<System.DateTime> RecDt { get; set; }
		}
}
