//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_ProductModel:Virtual_Spl_ProductModel
	{
		
	}
	public class Virtual_Spl_ProductModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "产品名称")]
		public virtual string Name { get; set; }
		[Display(Name = "产品代码")]
		public virtual string Code { get; set; }
		[Display(Name = "产品价格")]
		public virtual decimal Price { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<decimal> CostPrice { get; set; }
		[Display(Name = "产品颜色")]
		public virtual string Color { get; set; }
		[Display(Name = "产品数量")]
		public virtual decimal Number { get; set; }
		[Display(Name = "类别")]
		public virtual string CategoryId { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "未设置")]
		public virtual string CreateBy { get; set; }
		}
}
