//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.MIS
{

	public partial class MIS_WebIM_CommonTalkModel:Virtual_MIS_WebIM_CommonTalkModel
	{
		
	}
	public class Virtual_MIS_WebIM_CommonTalkModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string Talk { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<bool> State { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		}
}
