//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_WarehouseAllocationDetailsModel:Virtual_Spl_WarehouseAllocationDetailsModel
	{
		
	}
	public class Virtual_Spl_WarehouseAllocationDetailsModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string WareDetailsId { get; set; }
		[Display(Name = "未设置")]
		public virtual string WarehouseId { get; set; }
		[Display(Name = "未设置")]
		public virtual string WarehouseAllocationId { get; set; }
		[Display(Name = "未设置")]
		public virtual decimal Quantity { get; set; }
		[Display(Name = "未设置")]
		public virtual decimal Price { get; set; }
		[Display(Name = "未设置")]
		public virtual decimal TotalPrice { get; set; }
		[Display(Name = "未设置")]
		public virtual string Defined { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
