//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysLogModel:Virtual_SysLogModel
	{
		
	}
	public class Virtual_SysLogModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "操作人")]
		public virtual string Operator { get; set; }
		[Display(Name = "操作信息")]
		public virtual string Message { get; set; }
		[Display(Name = "结果")]
		public virtual string Result { get; set; }
		[Display(Name = "类型")]
		public virtual string Type { get; set; }
		[Display(Name = "对应模块")]
		public virtual string Module { get; set; }
		[Display(Name = "操作时间")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		}
}
