//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Flow
{

	public partial class Flow_FormContentStepCheckModel:Virtual_Flow_FormContentStepCheckModel
	{
		
	}
	public class Virtual_Flow_FormContentStepCheckModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "所属公文")]
		public virtual string ContentId { get; set; }
		[Display(Name = "所属步骤")]
		public virtual string StepId { get; set; }
		[Display(Name = "0不通过1通过2审核中")]
		public virtual int State { get; set; }
		[Display(Name = "状态(是否完成)")]
		public virtual bool StateFlag { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "是否结束")]
		public virtual bool IsEnd { get; set; }
		[Display(Name = "是否自选审核人默认为false")]
		public virtual bool IsCustom { get; set; }
		}
}
