//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.WC
{

	public partial class WC_ResponseLogModel:Virtual_WC_ResponseLogModel
	{
		
	}
	public class Virtual_WC_ResponseLogModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "所属公众号")]
		public virtual string OfficalAccountId { get; set; }
		[Display(Name = "OpenID")]
		public virtual string OpenId { get; set; }
		[Display(Name = "请求事件")]
		public virtual Nullable<int> RequestType { get; set; }
		[Display(Name = "请求模块名称")]
		public virtual string RequestContent { get; set; }
		[Display(Name = "相应的回复类别，text img media")]
		public virtual Nullable<int> ResponseType { get; set; }
		[Display(Name = "相应的信息，成功或者发送了什么")]
		public virtual string ResponseContent { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "创建人")]
		public virtual string CreateBy { get; set; }
		[Display(Name = "修改时间")]
		public virtual System.DateTime ModifyTime { get; set; }
		[Display(Name = "修改人")]
		public virtual string ModifyBy { get; set; }
		}
}
