//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_PersonModel:Virtual_Spl_PersonModel
	{
		
	}
	public class Virtual_Spl_PersonModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string Name { get; set; }
		[Display(Name = "未设置")]
		public virtual string Sex { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<int> Age { get; set; }
		[Display(Name = "未设置")]
		public virtual string IDCard { get; set; }
		[Display(Name = "未设置")]
		public virtual string Phone { get; set; }
		[Display(Name = "未设置")]
		public virtual string Email { get; set; }
		[Display(Name = "未设置")]
		public virtual string Address { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "未设置")]
		public virtual string Region { get; set; }
		[Display(Name = "未设置")]
		public virtual string Category { get; set; }
		}
}
