//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.WC
{

	public partial class WC_UserModel:Virtual_WC_UserModel
	{
		
	}
	public class Virtual_WC_UserModel
	{
		[Display(Name = "OpenId主键")]
		public virtual string Id { get; set; }
		[Display(Name = "OpenId")]
		public virtual string OpenId { get; set; }
		[Display(Name = "名称")]
		public virtual string NickName { get; set; }
		[Display(Name = "性别")]
		public virtual int Sex { get; set; }
		[Display(Name = "语言")]
		public virtual string Language { get; set; }
		[Display(Name = "城市")]
		public virtual string City { get; set; }
		[Display(Name = "省份")]
		public virtual string Province { get; set; }
		[Display(Name = "国家")]
		public virtual string Country { get; set; }
		[Display(Name = "头像")]
		public virtual string HeadImgUrl { get; set; }
		[Display(Name = "关注时间")]
		public virtual System.DateTime SubscribeTime { get; set; }
		[Display(Name = "未设置")]
		public virtual string UnionId { get; set; }
		[Display(Name = "说明")]
		public virtual string Remark { get; set; }
		[Display(Name = "所属组别")]
		public virtual string GroupId { get; set; }
		[Display(Name = "标签")]
		public virtual string TagidList { get; set; }
		[Display(Name = "是否关注")]
		public virtual int Subscribe { get; set; }
		[Display(Name = "所属公众号")]
		public virtual string OfficalAccountId { get; set; }
		}
}
