//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Flow
{

	public partial class Flow_ExternalModel:Virtual_Flow_ExternalModel
	{
		
	}
	public class Virtual_Flow_ExternalModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string Title { get; set; }
		[Display(Name = "未设置")]
		public virtual string Remark { get; set; }
		[Display(Name = "未设置")]
		public virtual string Photo { get; set; }
		[Display(Name = "未设置")]
		public virtual string SysUserId { get; set; }
		[Display(Name = "未设置")]
		public virtual string TrueName { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
