//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Flow
{

	public partial class Flow_StepRuleModel:Virtual_Flow_StepRuleModel
	{
		
	}
	public class Virtual_Flow_StepRuleModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "所属步骤")]
		public virtual string StepId { get; set; }
		[Display(Name = "字段ID")]
		public virtual string AttrId { get; set; }
		[Display(Name = "操作符号")]
		public virtual string Operator { get; set; }
		[Display(Name = "结果")]
		public virtual string Result { get; set; }
		[Display(Name = "下一步骤ID")]
		public virtual string NextStep { get; set; }
		}
}
