//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysExceptionModel:Virtual_SysExceptionModel
	{
		
	}
	public class Virtual_SysExceptionModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "帮助连接")]
		public virtual string HelpLink { get; set; }
		[Display(Name = "异常信息")]
		public virtual string Message { get; set; }
		[Display(Name = "来源类库")]
		public virtual string Source { get; set; }
		[Display(Name = "堆栈")]
		public virtual string StackTrace { get; set; }
		[Display(Name = "目标站点")]
		public virtual string TargetSite { get; set; }
		[Display(Name = "程序集")]
		public virtual string Data { get; set; }
		[Display(Name = "发生时间")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		}
}
