//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_EarlyWareingGoodModel:Virtual_Spl_EarlyWareingGoodModel
	{
		
	}
	public class Virtual_Spl_EarlyWareingGoodModel
	{
		[Display(Name = "GUI主键")]
		public virtual string Id { get; set; }
		[Display(Name = "货品名称")]
		public virtual string WareDetailsId { get; set; }
		[Display(Name = "最低库存")]
		public virtual decimal LowNumber { get; set; }
		[Display(Name = "库存")]
		public virtual decimal TotalNumber { get; set; }
		[Display(Name = "货品类别")]
		public virtual string ProductType { get; set; }
		[Display(Name = "货品单价")]
		public virtual decimal ProductPrice { get; set; }
		[Display(Name = "货品总价")]
		public virtual decimal PriceTotal { get; set; }
		[Display(Name = "未设置")]
		public virtual string WarehouseId { get; set; }
		[Display(Name = "更新时间")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
