//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysCalendarPlanModel:Virtual_SysCalendarPlanModel
	{
		
	}
	public class Virtual_SysCalendarPlanModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string Title { get; set; }
		[Display(Name = "未设置")]
		public virtual string PlanContent { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime BeginDate { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime EndDate { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "未设置")]
		public virtual string Url { get; set; }
		[Display(Name = "未设置")]
		public virtual string Color { get; set; }
		[Display(Name = "未设置")]
		public virtual string TextColor { get; set; }
		[Display(Name = "未设置")]
		public virtual string SysUserId { get; set; }
		[Display(Name = "未设置")]
		public virtual string Editable { get; set; }
		}
}
