//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.WC
{

	public partial class WC_GroupModel:Virtual_WC_GroupModel
	{
		
	}
	public class Virtual_WC_GroupModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "组别")]
		public virtual string Name { get; set; }
		[Display(Name = "合计")]
		public virtual int Count { get; set; }
		[Display(Name = "所属公众号")]
		public virtual string OfficalAccountId { get; set; }
		}
}
