//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.MIS
{

	public partial class MIS_Article_AlbumsModel:Virtual_MIS_Article_AlbumsModel
	{
		
	}
	public class Virtual_MIS_Article_AlbumsModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string ArticleId { get; set; }
		[Display(Name = "未设置")]
		public virtual string BigImg { get; set; }
		[Display(Name = "未设置")]
		public virtual string SmallImg { get; set; }
		[Display(Name = "未设置")]
		public virtual string Remark { get; set; }
		}
}
