//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Flow
{

	public partial class Flow_FormContentStepCheckStateModel:Virtual_Flow_FormContentStepCheckStateModel
	{
		
	}
	public class Virtual_Flow_FormContentStepCheckStateModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "所属步骤")]
		public virtual string StepCheckId { get; set; }
		[Display(Name = "审核人")]
		public virtual string UserId { get; set; }
		[Display(Name = "1通过0不通过2审核中")]
		public virtual int CheckFlag { get; set; }
		[Display(Name = "审核说明")]
		public virtual string Reamrk { get; set; }
		[Display(Name = "印章")]
		public virtual string TheSeal { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
