//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysRightDataFilterModel:Virtual_SysRightDataFilterModel
	{
		
	}
	public class Virtual_SysRightDataFilterModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "权限ID")]
		public virtual string RightId { get; set; }
		[Display(Name = "权限字段")]
		public virtual string KeyCode { get; set; }
		[Display(Name = "是否验证（暂时不用）")]
		public virtual bool IsValid { get; set; }
		}
}
