//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_WareCategoryModel:Virtual_Spl_WareCategoryModel
	{
		
	}
	public class Virtual_Spl_WareCategoryModel
	{
		[Display(Name = "主键ID")]
		public virtual string Id { get; set; }
		[Display(Name = "类别名称")]
		public virtual string Name { get; set; }
		[Display(Name = "类别编码")]
		public virtual string Code { get; set; }
		[Display(Name = "上级ID")]
		public virtual string ParentId { get; set; }
		[Display(Name = "说明")]
		public virtual string Remark { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "是否启用")]
		public virtual bool Enable { get; set; }
		}
}
