//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Apps.Common;
using System.Collections.Generic;
using Apps.Models.Sys;
namespace Apps.IBLL.Sys
{
	public partial interface ISysModuleBLL:IBaseBLL<SysModuleModel>
	{
      
	}
}
